### ISSUE TITLE
Uptime errors not published to user

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/widget-google-calendar#151] opened 2020-10-16 18:05 UTC
The following uptime errors are being reported, but they are not being published to the User:

- E000000062

**Comment by olegrise** [comment] 2020-10-27 14:36
@alanclayton @stulees  it looks like a firewall issue. I'm able to reproduce it by blocking URL in the browser. Also the fact that response code -1 indicates that the response is not coming from the server. The Calendar API does not return code -1  https://developers.google.com/calendar/v3/errors.
Just for the reference here is the full response 
```
{"error":{"code":-1,"message":"A network error occurred, and the request could not be completed."}} |  
```

**Comment by olegrise** [comment] 2020-10-27 15:06
@alanclayton @stulees widget makes a call to the `content.googleapis.com/calendar/v3/calendars/*` and the `*.googleapis.com` is included into network requirements https://help.risevision.com/hc/en-us/articles/115002459246-Rise-Player-network-requirements-

**Comment by stulees** [comment] 2020-10-27 15:22
@olegrise Thanks! @alanclayton To confirm, there is no action required right now. This defect will be addressed when we are publishing error to uptime and user. Keeping open until then.

**Comment by ezequielc** [comment] 2021-09-09 20:54
@stulees Closing as per https://github.com/Rise-Vision/rise-twitter/issues/70#issuecomment-916420515. Thanks

**Closed** 2021-09-09 20:55 UTC
