### ISSUE TITLE
Continous Scroll Does not Repeat in Interactive Presentations

### ISSUE THREAD

**Issue by mmeiers** [Rise-Vision/widget-google-calendar#100] opened 2016-01-04 19:36 UTC
Steps to reproduce:
1. Create an interactive presentation with a placeholder not on the home page.
2. Add the Google Calendar Widget to this placeholder.
3. Add a google calendar id to the widget, set scroll to continuously.

Result:
Once you navigate to the page that has the calendar widget autoscroll begins, but once it gets to the end of the event range it stops and does not fade out and return to the start of the events.
This appears to only happen with interactive presentation in placeholders that are placed in a page or index other than the one that initializes on startup (home page). This is not an issues with the component since scroll with text widget works in interactive presentations.

Example of Calendar widget inside interactive presentation working incorrectly (press green button):
http://rva.risevision.com/#/PRESENTATION_MANAGE/id=7a4eb864-d5cb-478a-8d6e-9a269eec35e5?cid=cb9c50b7-193c-4ada-bd72-f25b2202777c

How it should work:
Once the calendar widget reaches the end of the events it should fade out and return to the start (today).
Here is the same calendar widget outside of an interactive presentation working correctly:
http://rva.risevision.com/#/PRESENTATION_MANAGE/id=ff997a36-f737-4284-af75-fafc2ba39cbf?cid=cb9c50b7-193c-4ada-bd72-f25b2202777c

OS:
Chrome OS, Windows, Ubuntu

**Comment by alanclayton** [comment] 2016-01-04 20:46
@donnapep could you take a quick look and let me know what you think effort is for this?

**Comment by donnapep** [comment] 2016-01-04 21:18
@mmeiers @alanclayton I took a look, but it's not immediately apparent what the problem is. It does resume playback eventually. Given the uncertainty I'd estimate this as a 3. Thx.

**Comment by mmeiers** [comment] 2016-06-09 14:56
@donnapep @alanclayton Whats the status of this bug?
@sheadarlison Has discovered it in another presentation: 
http://rva.risevision.com/#/PRESENTATION_MANAGE/id=7db9cd1a-da01-4938-9143-7ccff4336433?cid=2a8fd875-38ed-4309-b548-d783e6910f3a

**Comment by alanclayton** [comment] 2016-06-09 14:57
@mmeiers we are going to address it our Calendar Epic which is up next after Spreadsheet. Can you wait a couple weeks?

**Comment by sheadarlison** [comment] 2016-06-09 14:59
@alanclayton Yeah we can wait. Thanks

**Comment by mmeiers** [comment] 2016-06-09 15:05
@alanclayton yep thanks

**Comment by donnapep** [comment] 2016-06-22 18:30
Fixed by PR #103.

**Closed by donnapep** 2016-06-22 18:30 UTC
