### ISSUE TITLE
When calendar does not fill placeholder, scrolling breaks PUD.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/widget-google-calendar#96] opened 2015-08-10 21:46 UTC
Steps to reproduce:
1. Create a presentation with a full screen placeholder.
2. Add the Google Calendar Widget to this placeholder.
3. Add a google calendar to the widget, set scroll to continuously.
4. Add any other content to placeholder (text item), set this content to play for 10 seconds.
5. Set calendar to Play Until Done.

Result:
The presentation will play the text item, then the calendar. The calendar will remain on the screen and never cycle back to the text item.

How it should work:
Placeholder should respect Play Until Done, even when there is not enough content to scroll.

Link to Presentation:
http://rva.risevision.com/#/PRESENTATION_MANAGE/id=9f8ac06f-8674-40ad-81bd-a85496a7c1ba?cid=fee1f642-cdd1-4bc4-8f93-1fc97cb00d55

OS:
Chrome OS, Windows, Ubuntu, OS X.

Chrome Ver:
44.x

**Comment by donnapep** [comment] 2015-08-11 12:35
@btfrise Are you saying that if there is not enough content to scroll, the Calendar never moves to the next item in the Playlist? Or it never moves to the next Playlist item at all?

If the former, that would be expected behaviour because in that case there is no definition of "done". What would "done" mean in the situation where there is no scrolling content?

If the latter, then only the case where content scrolls would be able to be addressed.

**Comment by btfrise** [comment] 2015-08-11 13:05
@donnapep The former. hen there is not enough content to scroll, the Calendar never moves onto the next item in the playlist.

**Comment by donnapep** [comment] 2015-08-11 13:13
@btfrise OK, then I think this is a non-issue since there is no way to determine what "done" means when content does not scroll. Unless you have some idea of how to define it in this case?

**Comment by btfrise** [comment] 2015-08-11 13:21
@donnapep I think this is the problem:

Tuesday's calendar has enough content to cause the placeholder to scroll, it moves onto the other items in the placeholder as needed.

Wednesday's calendar does not have enough content to scroll, it never displays the other items in the placeholder.

**Comment by donnapep** [comment] 2015-08-11 13:53
@btfrise If I preview the Presentation above, I see events for Wednesday and Thursday. They do not fill the Placeholder and so they do not scroll. I'm still unsure of what should happen at this point? When should the Widget send Done so that the Playlist moves to the next item?

**Comment by btfrise** [comment] 2015-08-11 14:09
@donnapep I'm not sure when it should send the done command. Maybe PUD should default to a certain amount of time if there is no scroll? This is something you and @alanclayton should work out.

This is not functioning in a user friendly way at this time and needs to be resolved.

**Comment by alanclayton** [comment] 2015-08-11 14:44
@donnapep if we don't have information available to determine when Done is could we just fall back to using the duration for that item?

**Comment by donnapep** [comment] 2015-08-11 14:47
@alanclayton The Widget doesn't actually know what its duration is. Only the Viewer knows that.

**Comment by alanclayton** [comment] 2016-02-02 21:44
This is no longer an issue. Resolved by adding PUD Failover setting on Widget.

**Closed by alanclayton** 2016-02-02 21:44 UTC
Labels: bug
